In [1]:
import numpy as np
x=np.ones((3,5),dtype=np.int8)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [2]:
x=np.arange(1334,1339,2)
x

array([1334, 1336, 1338])

In [3]:
import numpy as np

# 1. Broadcasting
# a) Add a 1D array `[1, 2, 3]` to each row of a 2D array `[[10, 20, 30], [40, 50, 60]]`.
# Expected: [[11, 22, 33], [41, 52, 63]]
arr = np.array([[10, 20, 30], [40, 50, 60]])
arr1 = np.array([1,2,3])
print(arr+arr1)

# b) Multiply a 2D array `[[1, 2], [3, 4]]` by a 1D array `[10, 20]` column-wise.
# Expected: [[10, 20], [60, 80]]

arr = np.array([[1,2],[3,4]])
arr1 = np.array([[10],[20]])
print(arr*arr1)

[[11 22 33]
 [41 52 63]]
[[10 20]
 [60 80]]


In [34]:
# 2. Indexing and Slicing (High Dimensional Arrays)
arr = np.arange(1, 25).reshape(2, 3, 4)
print ("2a")
print(arr)
# a) Extract the second slice along axis 0.
# Expected: [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]

# b) Extract all rows and the last column for all slices.
# Expected: [[4, 8, 12], [16, 20, 24]]
print ("2b")
print(arr[:,:,-1])
# c) Reverse the order of slices along axis 0.
# Expected: [[[13, 14, 15, 16], ...], [[1, 2, 3, 4], ...]]
print ("2c")
reversed_arr = arr[::-1]
print(reversed_arr)
print ("2c")
a1 = np.flip(arr,axis=0)
print(a1)
# d) Set all even elements in the array to -1.
# Expected: All even numbers replaced by -1.
print ("2d")
arr[arr%2 ==0] = -1
arr    
                

2a
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
2b
[[ 4  8 12]
 [16 20 24]]
2c
[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
2c
[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
2d


array([[[ 1, -1,  3, -1],
        [ 5, -1,  7, -1],
        [ 9, -1, 11, -1]],

       [[13, -1, 15, -1],
        [17, -1, 19, -1],
        [21, -1, 23, -1]]])

In [49]:
# 3. np.repeat
# a) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where every odd element is repeated twice.
# Expected: [1, 1, 3, 3, 5, 5]
print("3a")
arr = np.array([1, 2, 3, 4, 5, 6])
original = arr.copy()
for i in range(arr.shape[0]-1):
    if original[i]%2 != 0:
        arr[i+1] = original[i]
print(arr)        
# b) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where elements are repeated based on their value.
# For example, `1` is repeated once, `2` twice, etc.
# Expected: [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, ...]
print("3b")
arr = np.array([1, 2, 3, 4, 5, 6])
arr = np.repeat(arr,arr)
print(arr)

3a
[1 1 3 3 5 5]
3b
[1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6]


In [57]:
# 4. Normalizing
# a) Normalize a 1D array `arr = np.array([10, 20, 30])` to have values between 0 and 1.
# Expected: [0.0, 0.5, 1.0]
arr = np.array([10, 20, 30])
normalized = (arr-arr.min()) / (arr.max()-arr.min())
normalized

array([0. , 0.5, 1. ])

In [77]:
# 5. Bonus Challenge
# a) Create a 3x3 matrix where each element at position (i, j) is i * j.
# Expected: [[0, 0, 0], [0, 1, 2], [0, 2, 4]]
arr = np.fromfunction(lambda i,j : i*j,(3,3),dtype=int)
print(arr)
# b) Given a 4x4 matrix, replace all elements on the main diagonal with 0 without using a loop.
# Expected: Diagonal elements replaced with 0.
print("5b")
arr = np.ones((4,4),dtype=int)
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if i ==j:
            arr[i][j] = 0
arr            

[[0 0 0]
 [0 1 2]
 [0 2 4]]
5b


array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [ ]:
arr = np.ones((3,3))
print("5a")
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        arr[i][j] = i*j
print(arr)
        

[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]
